name: Compile exteplayer3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libavutil-dev \
          libswresample-dev \
          libasound2-dev \
          libpthread-stubs0-dev

    - name: Compile exteplayer3
      run: |
        make -j$(nproc)
